version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./app:/work
  
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./app:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: